# Generated by Django 6.0.2 on 2026-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("ToDo", "Todo"),
                    ("Done", "Done"),
                    ("In Progress", "In Progress"),
                ],
                null=True,
            ),
        ),
    ]
