# Generated by Django 6.0.2 on 2026-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To-do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='TODO', max_length=11),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_page',
            field=models.CharField(choices=[('AGENDA', 'Agenda'), ('CALENDAR', 'Calendar'), ('KANBAN', 'Kanban'), ('PROJECT', 'Project')], default='agenda', max_length=8),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='light', max_length=5),
        ),
    ]
