# Generated by Django 6.0.2 on 2026-03-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_description_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
    ]
