# Generated by Django 6.0.2 on 2026-03-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_id_project_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='parent_task_id',
            new_name='parent_task',
        ),
    ]
